# Generated by Django 3.2.16 on 2023-03-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='stream',
            field=models.ManyToManyField(to='chat.Stream'),
        ),
    ]
