# Generated by Django 3.2.16 on 2023-03-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_call',
            field=models.BooleanField(default=False),
        ),
    ]
