# Generated by Django 3.2.16 on 2023-03-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_is_in_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='chat.chat')),
                ('connected_users', models.ManyToManyField(blank=True, related_name='connected_breakout_rooms', to='chat.User')),
                ('participants', models.ManyToManyField(related_name='breakout_rooms', to='chat.User')),
                ('stream', models.ManyToManyField(to='chat.Stream')),
            ],
        ),
    ]
